package constant

const (
	ACTION_MASTER_DATA = "ACTION_MASTER_DATA"
	LOG_BODY_DATA      = "LOG_BODY_DATA"
	LOG_HEADER_DATA    = "LOG_HEADER_DATA"
	LOG_RESPONSE_DATA  = "LOG_RESPONSE_DATA"
	MENU_CHILD_DATA    = "MENU_CHILD_DATA"
	MENU_MASTER_DATA   = "MENU_MASTER_DATA"
	ROLE_ACTION_DATA   = "ROLE_ACTION_DATA"
	ROLE_MASTER_DATA   = "ROLE_MASTER_DATA"
	ROLE_MENU_DATA     = "ROLE_MENU_DATA"
	USER_APP_DATA      = "USER_APP_DATA"
	USER_LOGIN_DATA    = "USER_LOGIN_DATA"
	USER_MASTER_DATA   = "USER_MASTER_DATA"
	USER_PASSWORD_DATA = "USER_PASSWORD_DATA"
	USER_ROLE_DATA     = "USER_ROLE_DATA"
	SYSTEM_MASTER_DATA = "SYSTEM_MASTER_DATA"
)
